#!/bin/sh
# Services système essentiels de ConsoleOS
case "$1" in
  start)
    echo "[ConsoleOS] Démarrage des services système..."
    /usr/bin/consoleos-notifyd &
    /usr/bin/consoleos-padd &
    /usr/bin/consoleos-updated --watch /media &
    ;;
  stop)
    killall consoleos-notifyd consoleos-padd consoleos-updated 2>/dev/null
    ;;
  *) echo "usage: $0 {start|stop}" ;;
esac
